service-base-chart:
  applicationName: kamino-airdrop-api
  image:
    repository: hubbleprotocol/kamino-airdrop-api
    tag: latest
  envVars:
   - name: MINT
     value: KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS
   - name: BASE
     value: GKcx3UXQwUEnfAUzumN5BgvoKNFHb9fBZbG9jiKE5Bz7

  containerPorts:
  - name: http
    containerPort: 7001
    protocol: TCP

  readinessProbe:
    path: /health
    periodSeconds: 10
    timeoutSeconds: 2
  livenessProbe:
    path: /health
    periodSeconds: 10
    timeoutSeconds: 2
  startupProbe:
    path: /health
    periodSeconds: 10
    timeoutSeconds: 2
    initialDelaySeconds: 3
