service-base-chart:
  applicationName: kamino-airdrop-api
  image:
    repository: hubbleprotocol/kamino-airdrop-api
    tag: latest
  envVars:
   - name: MINT
     value: GwjzR5QkgBw4aQAxkJTCE6Uuw7za4kRn7x9Df45qCZkW
   - name: BASE
     value: cVQ72JNx6VXrBtfzVc77UbAhF4PvQ2UyvqDmBGxCTUs

  containerPorts:
  - name: http
    containerPort: 7001
    protocol: TCP

  readinessProbe:
    path: /health
    periodSeconds: 10
    timeoutSeconds: 2
  livenessProbe:
    path: /health
    periodSeconds: 10
    timeoutSeconds: 2
  startupProbe:
    path: /health
    periodSeconds: 10
    timeoutSeconds: 2
    initialDelaySeconds: 3
