name: API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build_docker:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.set_versions.outputs.build_version }}
      release_version: ${{ steps.set_versions.outputs.release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set versions
        id: set_versions
        shell: bash
        working-directory: ./
        run: ./.github/scripts/set-cargo-build-versions.sh
      - name: Set docker cache key
        env:
          BRANCH: "${{ github.head_ref || github.ref_name }}"
        run: |
          DOCKER_CACHE_KEY=${{ env.BRANCH }}
          DOCKER_CACHE_KEY=$(echo $DOCKER_CACHE_KEY | sed 's#/#_#g') # replace all slashes with underscores
          echo DOCKER_CACHE_KEY=${DOCKER_CACHE_KEY} >> $GITHUB_ENV # update GitHub ENV vars
      - name: Docker buildx (build)
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          secrets: |
            "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID_DISTRIBUTOR_BUILD }}"
            "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY_DISTRIBUTOR_BUILD }}"
          file: ./api/Dockerfile
          tags: hubbleprotocol/kamino-airdrop-api:${{ steps.set_versions.outputs.build_version }}
          push: true
          target: runtime
          cache-from: |
            type=registry,ref=hubbleprotocol/kamino-airdrop-api:${{ env.DOCKER_CACHE_KEY }} 
            type=registry,ref=hubbleprotocol/kamino-airdrop-api:master
          cache-to: type=registry,mode=max,ref=hubbleprotocol/kamino-airdrop-api:${{ env.DOCKER_CACHE_KEY }}
  build_helm:
    needs: build_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Helm build
        id: helm_build
        uses: docker/build-push-action@v4
        with:
          file: ./.github/docker/helm.Dockerfile
          tags: hubbleprotocol/kamino-airdrop-api-helm-build:${{ needs.build_docker.outputs.build_version }}
          push: false
          secrets: |
            "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID_HELM_REPO }}"
            "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY_HELM_REPO }}"
          build-args: |
            "CHART=kamino-airdrop-api"
            "DIR=api"
            "BUILD_VERSION=${{ needs.build_docker.outputs.build_version }}"
  publish_release_events:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - build_docker
      - build_helm
    runs-on: ubuntu-latest
    steps:
      - name: Publish release event kamino-airdrop-api
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HUBBLEPROTOCOLBOT_WRITE_REPO_PAT }}
          repository: hubbleprotocol/hubble-infrastructure
          event-type: helm-release
          client-payload: '{"name": "kamino-airdrop-api", "namespace": "api", "sub_dir": "kamino-airdrop-api", "build_version": "${{ needs.build_docker.outputs.build_version }}", "release_version": "${{ needs.build_docker.outputs.release_version }}", "changelog_url": "${{ github.server_url }}/${{ github.repository }}/releases/tag/kamino-airdrop-api%2F${{ needs.build_docker.outputs.release_version }}", "envs": ["dev", "prod"]}'
  pre_release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - build_docker
      - build_helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Fetch release artifact
        id: fetch_release_bin
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          tags: hubbleprotocol/kamino-airdrop-api-release-bin:${{ needs.build_docker.outputs.build_version }}
          push: false
          target: release-bin
          outputs: 'type=tar,dest=kamino-airdrop-api-${{ needs.build_docker.outputs.build_version }}.tar'
          cache-from: |
            type=registry,ref=hubbleprotocol/kamino-airdrop-api:master
      - name: Create pre-release
        id: pre_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: kamino-airdrop-api/${{ needs.build_docker.outputs.release_version }}
          prerelease: true
          title: kamino-airdrop-api/${{ needs.build_docker.outputs.release_version }}
          files: |
            kamino-airdrop-api-*.tar
