name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install essential
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev
      - uses: dtolnay/rust-toolchain@1.73.0
        with:
          components: rustfmt
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        name: Rust format
        with:
          toolchain: nightly
          command: fmt
          args: --all -- --check
      - uses: actions-rs/clippy-check@v1
        name: Clippy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
